name: Deploy Chirp Remote DB

on:
  push:
    branches:
      - Chirp-cli-Azure
    paths:
      - "src/Chirp.CSVDB.Service/**"
      - ".github/workflows/deploy-remotedb.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore src/Chirp.CSVDB.Service/Chirp.CSVDB.Service.csproj

      - name: Build
        run: dotnet build src/Chirp.CSVDB.Service/Chirp.CSVDB.Service.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish src/Chirp.CSVDB.Service/Chirp.CSVDB.Service.csproj -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: bdsagroup23chirpremotedb
          publish-profile: ${{ secrets.AZURE_REMOTE_DB_PUBLISH_PROFILE }}
          package: publish
